workflows:
  ios-workflow:
    name: iOS Production
    instance_type: mac_mini_m1
    environment:
      vars:
        BUNDLE_ID: "tunedtech.uk.tunedJobs"
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        APP_STORE_APPLE_ID: "olayemi.abdullahi9585@gmail.com"   # Set the Apple ID here
      groups:
        - app_store_credentials    # Add environment variable group
      xcode: latest
      cocoapods: default
      flutter: stable
      ios_signing:
        provisioning_profiles:
          - "tunedtech.uk.tunedJobs"   # Your provisioning profile for iOS
        certificates:
          - distribution  # Your distribution certificate
    cache:
      cache_paths:
        - ~/.pub-cache
        - $FLUTTER_ROOT/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
    scripts:
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --apple-id "$APP_STORE_APPLE_ID" \
            --password "$APP_STORE_PASSWORD"
          keychain add-certificates
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Flutter build
        script: |
          flutter build ios --release --no-codesign
      - name: Build iOS
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --config Release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        apple_id: "$APP_STORE_APPLE_ID"
        password: "$APP_STORE_PASSWORD"
        submit_to_testflight: true
        submit_to_app_store: true
        beta_groups:
          - "Internal Testers"
