workflows:
  ios-workflow:
    name: iOS Production
    instance_type: mac_mini_m1 # Or a larger instance if needed
    environment:
      vars:
        BUNDLE_ID: "tunedtech.uk.tunedJobs"
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY # API Key
        APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER # Key ID
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID # Issuer ID
        # Optional:
        FLUTTER_DEBUG: true
        COCOAPODS_DISABLE_STATS: true
    xcode: "15.0" # Or "latest" for the latest Xcode 15.x
    cocoapods: default
    flutter: stable
    ios_signing:
      provisioning_profiles:
        - abdul # Make sure this profile is for DISTRIBUTION (App Store)
      certificates:
        - development_Certificates # Make sure this certificate is for DISTRIBUTION
    cache:
      cache_paths:
        - ~/.pub-cache
        - $FLUTTER_ROOT/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update # Simplified

      - name: Flutter build
        script: |
          flutter build ios --release --no-codesign # Important: No code signing here
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: true
        beta_groups:
          - "tuned group"