workflows:
  ios-method-1:
    name: iOS Build and Release
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: tunedtech.uk.tunedJobs  # ✅ Corrected Bundle Identifier
    scripts:
      - name: Install Dependencies
        script: |
          flutter pub get
          cd ios
          pod install --repo-update

      - name: Increment Build Number
        script: flutter pub run version:bump patch  # Adjust as needed

      - name: Build Flutter App (No Signing)
        script: |
          flutter build ios --release --no-codesign  # Important: No codesign here!

      - name: Export IPA
        script: |
          cd ios
          xcodebuild -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath build/Runner.xcarchive \
            archive

          xcodebuild -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath build/ios/ipa

    artifacts:
      - build/ios/ipa/*.ipa  # ✅ Downloadable IPA file

    publishing:
      email:
        recipients:
          - your.email@example.com  # **Your email for receiving the build**
