workflows:
  ios-workflow:
    name: iOS Production
    instance_type: mac_mini_m1
    environment:
      vars:
        BUNDLE_ID: "tunedtech.uk.tunedJobs"
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY
        APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
        FLUTTER_DEBUG: true
        COCOAPODS_DISABLE_STATS: true
      xcode: "15.0"
      cocoapods: default
      flutter: stable
      ios_signing:
        provisioning_profiles:
          - abdul
        certificates:
          - distribution_Certificates
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter clean
          flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update

      - name: Flutter build
        script: |
          flutter build ios --release --no-codesign

      - name: Build iOS IPA
        script: |
          cd ios
          xcodebuild -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath build/Runner.xcarchive \
            archive \
            -allowProvisioningUpdates \
            DEVELOPMENT_TEAM="UVARSZGUFK"

          xcodebuild -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath build/ios/ipa \
            -allowProvisioningUpdates
    artifacts:
      - ios/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log