workflows:
  ios-workflow:
    name: iOS Production
    instance_type: mac_mini_m1
    environment:
      vars:
        BUNDLE_ID: "tunedtech.uk.tunedJobs"
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        APP_STORE_APPLE_ID: olayemi.abdullahi9585@gmail.com
        APP_SPECIFIC_PASSWORD: jhiv-spnz-rgpj-wfbo
        # Add these environment variables
        FLUTTER_DEBUG: true
        COCOAPODS_DISABLE_STATS: true
      xcode: latest
      cocoapods: default
      flutter: stable
      ios_signing:
        provisioning_profiles:
          - abdul
        certificates:
          - development_Certificates
    cache:
      cache_paths:
        - ~/.pub-cache
        - $FLUTTER_ROOT/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
    scripts:
      - name: Update iOS deployment target and build settings
        script: |
          cd ios
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = .*;/IPHONEOS_DEPLOYMENT_TARGET = 12.0;/' Podfile
          # Add post_install hook with architecture settings
          cat >> Podfile << 'EOL'
          
          post_install do |installer|
            installer.pods_project.targets.each do |target|
              flutter_additional_ios_build_settings(target)
              target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
                config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
                config.build_settings["DEVELOPMENT_TEAM"] = "YOUR_TEAM_ID" # Replace with your team ID
                config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
              end
            end
          end
          EOL
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --apple-id "$APP_STORE_APPLE_ID" \
            --password "$APP_SPECIFIC_PASSWORD"
          keychain add-certificates
      - name: Install Flutter dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          rm -rf Pods/
          rm -rf Podfile.lock
          pod repo update
          pod deintegrate
          pod setup
          pod install --repo-update
      - name: Flutter build
        script: |
          flutter build ios --release --no-codesign
      - name: Manually Sign and Build iOS
        script: |
          xcode-project use-profiles
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --config Release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: true
        beta_groups:
          - "Internal Testers"