workflows:
  ios-workflow:
    name: tuned Ios
    instance_type: mac_mini_m1
    environment:
      vars:
        BUNDLE_ID: "tunedtech.uk.tunedJobs"
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        FLUTTER_DEBUG: true
        COCOAPODS_DISABLE_STATS: true
        IPHONEOS_DEPLOYMENT_TARGET: "12.0"
      xcode: "15.0"
      cocoapods: default
      flutter: stable
      ios_signing:
        distribution_type: app_store  # or ad_hoc or development
        bundle_identifier: tunedtech.uk.tunedJobs
        provisioning_profiles:
          - "TunedJob"

    scripts:
      - name: Clean and Setup Environment
        script: |
          flutter clean
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          rm -rf ios/.symlinks
          rm -rf ios/Flutter/Flutter.framework
          rm -rf ios/Flutter/Flutter.podspec
          flutter pub get

      - name: Pod Setup and Install
        script: |
          cd ios
          pod deintegrate
          pod cache clean --all
          sed -i '' 's/platform :ios, '9.0'/platform :ios, '12.0'/' Podfile
          find . -name "*.podspec" -exec sed -i '' 's/\(s\.ios\.deployment_target\s*=\s*\)\("9.0"\|"10.0"\)/\112.0/' {} \;
          pod install --repo-update
          cd ..

      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles

      - name: Build IPA
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist \
            --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa