workflows:
  ios-method-1:
    name: iOS Build and Release
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: tunedtech.uk.tunedJobs  # **YOUR BUNDLE IDENTIFIER HERE**
    scripts:
      - name: Install Flutter
        script: |
          git clone https://github.com/flutter/flutter.git -b stable --depth 1
          export PATH="$PATH:`pwd`/flutter/bin"
          flutter --version

      - name: Install Dependencies
        script: |
          flutter pub get
          cd ios
          pod install --repo-update

      - name: Increment Build Number
        script: flutter pub run version:bump patch  # Adjust as needed

      - name: Build IPA
        script: |
          flutter build ipa --export-options-plist=ios/exportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - your.email@example.com  # **YOUR EMAIL HERE**
