workflows:
  ios-workflow:
    name: tuned Ios
    instance_type: mac_mini_m1
    environment:
      vars:
        BUNDLE_ID: "tunedtech.uk.tunedJobs" # Ensure this is correct
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY
        APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
        FLUTTER_DEBUG: true
        COCOAPODS_DISABLE_STATS: true
      xcode: "15.0" # Or specify the Xcode version you need
      cocoapods: default
      flutter: stable

    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter clean
          flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update

      - name: Flutter build
        script: |
          flutter build ios --release --no-codesign # Important: No codesign here!

      - name: Build and Sign IPA
        script: |
          cd ios
          xcodebuild -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath build/Runner.xcarchive \
            archive

          xcodebuild -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath build/ios/ipa

    artifacts:
      - build/ios/ipa/*.ipa  # Correct path

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true  # Or false
        submit_to_app_store: true
        beta_groups:
          - "tuned group" # Replace with your TestFlight group name
