workflows:
  ios-workflow:
    name: tuned Ios
    instance_type: mac_mini_m1
    environment:
      vars:
        BUNDLE_ID: "tunedtech.uk.tunedJobs"
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY
        APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
        FLUTTER_DEBUG: true
        COCOAPODS_DISABLE_STATS: true
      xcode: "15.0"
      cocoapods: default
      flutter: stable

      ios_signing:
        automatic: true
        team_id: "UVARSZGUFK"
        distribution_type: app_store
        bundle_identifier: tunedtech.uk.tunedJobs

    scripts:
      - name: Set up environment
        script: |
          flutter doctor -v
          xcodebuild -version

      - name: Install Flutter dependencies
        script: |
          flutter clean
          flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update

      - name: Build and Sign IPA
        script: |
          cd ios
          # Create archive
          xcodebuild -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath build/Runner.xcarchive \
            archive \
            -allowProvisioningUpdates

          # Export IPA
          xcodebuild -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath build/ios/ipa \
            -allowProvisioningUpdates

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: true
        beta_groups:
          - "tuned group"

    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/Library/Developer/Xcode/DerivedData