workflows:
  ios-workflow:
    name: tuned Ios
    instance_type: mac_mini_m1
    environment:
      vars:
        BUNDLE_ID: "tunedtech.uk.tunedJobs"
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY
        APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
        FLUTTER_DEBUG: true
        COCOAPODS_DISABLE_STATS: true
        IPHONEOS_DEPLOYMENT_TARGET: "12.0"
      xcode: "15.0"
      cocoapods: default
      flutter: stable

    scripts:
      - name: Clean and Setup Environment
        script: |
          flutter clean
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          rm -rf ios/.symlinks
          rm -rf ios/Flutter/Flutter.framework
          rm -rf ios/Flutter/Flutter.podspec
          flutter pub get

      - name: Pod Setup and Install
        script: |
          cd ios
          pod deintegrate
          pod cache clean --all
          sed -i '' 's/platform :ios, '9.0'/platform :ios, '12.0'/' Podfile
          find . -name "*.podspec" -exec sed -i '' 's/\(s\.ios\.deployment_target\s*=\s*\)\("9.0"\|"10.0"\)/\112.0/' {} \;
          pod install --repo-update
          cd ..

      - name: Configure Xcode Project
        script: |
          xcode-project use-profiles

      - name: Build IPA
        script: |
          flutter build ipa --release --export-options-plist /Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: true
        beta_groups:
          - "tuned group"