workflows:
  ios-workflow:
    name: iOS Production
    instance_type: mac_mini_m1
    environment:
      vars:
        BUNDLE_ID: "tunedtech.uk.tunedJobs"
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY
        APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
        FLUTTER_DEBUG: true
        COCOAPODS_DISABLE_STATS: true
      xcode: "15.0"
      cocoapods: default
      flutter: stable
      ios_signing:
        provisioning_profiles:
          - abdul
        certificates:
          - distribution_Certificates  # Changed from development to distribution
    scripts:
      - name: Set up code signing
        script: |
          keychain initialize

      - name: Install Flutter dependencies
        script: |
          flutter clean
          flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update

      - name: Update Pod deployment targets
        script: |
          cd ios
          sed -i '' 's/platform :ios, '"'"'.*'"'"'/platform :ios, '"'"'12.0'"'"'/' Podfile
          pod install

      - name: Flutter build
        script: |
          flutter build ios --release

      - name: Build iOS IPA
        script: |
          cd ios
          xcodebuild -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath build/Runner.xcarchive \
            archive \
            CODE_SIGN_STYLE=Manual \
            PROVISIONING_PROFILE="abdul" \
            DEVELOPMENT_TEAM="ABDULLAHI AFOLARIN"  # Replace with your team ID
          
          xcodebuild -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath build/ios/ipa
    artifacts:
      - ios/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log