// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpLXaP5K3MEhAYFx4a7EpK6oH16On8_MY',
    appId: '1:315632173712:web:71b17538da43910e2fce15',
    messagingSenderId: '315632173712',
    projectId: 'tunedjobss',
    authDomain: 'tunedjobss.firebaseapp.com',
    storageBucket: 'tunedjobss.firebasestorage.app',
    measurementId: 'G-CVZJKKPCVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmA1uwnFCAjvEpdy7HGUvlSGRiSSO1o-E',
    appId: '1:315632173712:android:01b310e789829aa02fce15',
    messagingSenderId: '315632173712',
    projectId: 'tunedjobss',
    storageBucket: 'tunedjobss.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRbTQj7kdY1aZqDamG43I3oLL7DsemHqM',
    appId: '1:315632173712:ios:3628a7f0970a44622fce15',
    messagingSenderId: '315632173712',
    projectId: 'tunedjobss',
    storageBucket: 'tunedjobss.firebasestorage.app',
    iosBundleId: 'tunedtech.uk.tunedJobs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRbTQj7kdY1aZqDamG43I3oLL7DsemHqM',
    appId: '1:315632173712:ios:3628a7f0970a44622fce15',
    messagingSenderId: '315632173712',
    projectId: 'tunedjobss',
    storageBucket: 'tunedjobss.firebasestorage.app',
    iosBundleId: 'tunedtech.uk.tunedJobs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpLXaP5K3MEhAYFx4a7EpK6oH16On8_MY',
    appId: '1:315632173712:web:866ff688816989a02fce15',
    messagingSenderId: '315632173712',
    projectId: 'tunedjobss',
    authDomain: 'tunedjobss.firebaseapp.com',
    storageBucket: 'tunedjobss.firebasestorage.app',
    measurementId: 'G-PTW9NTWMK3',
  );
}
